spring:
  application:
    name: order
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zma6611/config-repo.git
          username: 351457250@qq.com
          password: DAvID16KaDsL
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev
server:
  port: 8081
